# Generated by Django 5.0.1 on 2024-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('local', 'Local'), ('tournament', 'Tournament'), ('remote', 'Remote'), ('disconnected', 'Disconnected')], default='disconnected', max_length=12),
        ),
    ]
