# Generated by Django 5.0.1 on 2024-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=10)),
                ('player2_name', models.CharField(max_length=10)),
                ('player3_name', models.CharField(max_length=10)),
                ('player4_name', models.CharField(max_length=10)),
                ('first_winner', models.CharField(null=True)),
                ('second_winner', models.CharField(null=True)),
                ('final_winner', models.CharField(null=True)),
                ('game_turn', models.IntegerField(default=1)),
            ],
        ),
    ]
