# Generated by Django 5.0.1 on 2024-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('default', 'default'), ('extreme', 'extreme')], max_length=7),
        ),
    ]
