# Generated by Django 5.0.1 on 2024-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('default', 'Default'), ('extreme', 'Extreme')], max_length=7),
        ),
    ]
