# Generated by Django 5.0.1 on 2024-02-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('DEF', 'Default'), ('EXT', 'Extreme')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
