version: "3.9"
   
services:
  nginx:
    build: ./nginx
    volumes:
      - ./certs/nginx/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    command: sh /scripts/top-entrypoint.sh
    volumes:
      - ./backend/srcs/:/code
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .env
    restart: always
  
volumes:
  postgres_data: {}
