version: "3.9"
   
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    command: sh /scripts/top-entrypoint.sh
    volumes:
      - ./backend/srcs/:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    platform: linux/amd64
    ports:
      - "5003:5003"
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
    # depends_on:
    #   - elasticsearch
  
volumes:
  postgres_data: {}
