version: "3.9"

services:
  backend:
    build: .
    volumes:
      - ./srcs/:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  
volumes:
  postgres_data:
