# Generated by Django 5.0.1 on 2024-02-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField()),
                ('player2_name', models.CharField()),
                ('game_mode', models.CharField(choices=[('default', 'Default'), ('extreme', 'Extreme')], max_length=7)),
            ],
        ),
    ]
